apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spark-history-server.baseName" . }}-env
data:
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
