{{- if .Values.serviceaccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "spark-history-server.serviceAccountName" . }}
  {{- template "spark-history-server.commonLabels" . }}
{{- end }}
