{{- if .Values.serviceaccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "spark-history-server.baseName" . }}
  labels:
    {{- include "spark-history-server.commonLabels" . | nindent 4 }}
{{- end }}
