apiVersion: v1
kind: Service
metadata:
  name : {{ template "spark-history-server.baseName" . }}-{{ .Release.Name }}
  {{- template "spark-history-server.commonLabels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: history-port
      protocol: TCP
      name: http-port
  selector:
      app.kubernetes.io/name: {{ template "spark-history-server.baseName" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
